# Generated by Django 4.2 on 2024-08-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Eléctrico'), ('A', 'Agua'), ('F', 'Fuego'), ('P', 'Planta'), ('T', 'Tierra')], max_length=30),
        ),
    ]
